Controllers/MesuesisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ligjerata_7___xhelali2.Data;
using Ligjerata_7___xhelali2.Models;
using Microsoft.AspNetCore.Authorization;

namespace Ligjerata_7___xhelali2.Controllers
{
    [Authorize]
    public class MesuesisController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MesuesisController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Mesuesis
        public async Task<IActionResult> Index(int pg = 1)
        {
            //return View(await _context.Mesuesi.ToListAsync());


            List<Mesuesi> mesuesi= _context.Mesuesi.ToList();

            const int pageSize = 5;
            if (pg < 1)
                pg = 1;

            int recsCount = mesuesi.Count();
            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;
            var data = mesuesi.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;
            //return View(await _context.Students.ToListAsync());
            return View(data);
        }


       


        // GET: Mesuesis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Mesuesi == null)
            {
                return NotFound();
            }

            var mesuesi = await _context.Mesuesi
                .FirstOrDefaultAsync(m => m.id == id);
            if (mesuesi == null)
            {
                return NotFound();
            }

            return View(mesuesi);
        }

        // GET: Mesuesis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Mesuesis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,Surname,Photo, Image")] Mesuesi mesuesi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mesuesi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mesuesi);
        }

        // GET: Mesuesis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Mesuesi == null)
            {
                return NotFound();
            }

            var mesuesi = await _context.Mesuesi.FindAsync(id);
            if (mesuesi == null)
            {
                return NotFound();
            }
            return View(mesuesi);
        }

        // POST: Mesuesis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,Surname,Photo")] Mesuesi mesuesi)
        {
            if (id != mesuesi.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mesuesi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MesuesiExists(mesuesi.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mesuesi);
        }

        // GET: Mesuesis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Mesuesi == null)
            {
                return NotFound();
            }

            var mesuesi = await _context.Mesuesi
                .FirstOrDefaultAsync(m => m.id == id);
            if (mesuesi == null)
            {
                return NotFound();
            }

            return View(mesuesi);
        }

        // POST: Mesuesis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Mesuesi == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Mesuesi'  is null.");
            }
            var mesuesi = await _context.Mesuesi.FindAsync(id);
            if (mesuesi != null)
            {
                _context.Mesuesi.Remove(mesuesi);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MesuesiExists(int id)
        {
          return _context.Mesuesi.Any(e => e.id == id);
        }
    }
}

Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ligjerata_7___xhelali2.Data;
using Ligjerata_7___xhelali2.Models;
using Microsoft.AspNetCore.Authorization;
using NuGet.Protocol.Core.Types;

namespace Ligjerata_7___xhelali2.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index(int pg=1)
        {
            List<Student> student = _context.Students.ToList();

            const int pageSize = 5;
            if (pg < 1)
                pg = 1;

            int recsCount = student.Count();
            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;
            var data = student.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;
            //return View(await _context.Students.ToListAsync());
            return View(data);
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Email")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Email")] Student student)
            {
                if (id != student.Id)
                {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Students'  is null.");
            }
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        //FILTRIMI TEST


        private bool StudentExists(int id)
        {
          return _context.Students.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ligjerata_7___xhelali2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ligjerata_7___xhelali2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               <img src="">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E-Shkollori</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="index">Lista e Studenteve</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mesuesis" asp-action="">Lista e Mesimdhenesve</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <section class="">
        <!-- Footer -->
        <footer class="text-center text-white fixed-bottom" style="background-color: #0a4275;">
            <!-- Grid container -->
            <div class="container p-4 pb-0">
                <!-- Section: CTA -->
                <section class="">
                    <p class="d-flex justify-content-center align-items-center">
                        <span class="me-3">Register for free</span>
                        <button type="button" class="btn btn-outline-light btn-rounded" asp-area="Identity" asp-controller="Account" asp-action="Register">
                            Sign up!
                        </button>
                    </p>
                </section>
                <!-- Section: CTA -->
            </div>
            <!-- Grid container -->
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                © 2020 Copyright:
                <a class="text-white" href="#">Jetmir & Bleart</a>
            </div>
            <!-- Copyright -->
        </footer>
        <!-- Footer -->
    </section>





    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>